main:
  - name: Home
    url: /
    weight: 10
  - name: Publications
    url: /publications/
    weight: 20
  - name: Projects
    url: /projects/
    weight: 30
  - name: Events
    url: /events/
    weight: 40
  - name: Blog
    url: /blog/
    weight: 50
